# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='user_id',
            new_name='user',
        ),
    ]
