# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170614_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
