# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_settings_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='pagination',
            field=models.IntegerField(default=10, max_length=10),
        ),
    ]
