# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_settings_pagination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='pagination',
            field=models.IntegerField(default=10),
        ),
    ]
