# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170702_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='date_time_format',
            field=models.CharField(default='relative', max_length=10),
        ),
    ]
