"""
Django settings for untitled1 project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import re

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY='9hl8z64xz3j=gh^f=l!=q#q49)4gte6p*=6f7_#xa&&3w0p+(l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG=True
TEMPLATE_DEBUG=False

ALLOWED_HOSTS=[]

# Application definition

INSTALLED_APPS=[
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    ##############
    'start',
    #############
    'account',
    'content',
    'settings',
    'editing',
    'category',
    'search',

]

MIDDLEWARE_CLASSES=[
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF='untitled1.urls'

TEMPLATES=[
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        },
    },
]

WSGI_APPLICATION='untitled1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES={
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# #
# DATABASES={
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # 'NAME': os.path.abspath(os.path.join(BASE_DIR, 'db.sqlite3')),
#         'NAME': 'pinmyblogs',
#         'HOST': "127.0.0.1",
#         "PORT": '3306',
#         "USER": "root",
#         "PASSWD": ""
#
#     }
#     #
# }
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS=[
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE='en-us'

TIME_ZONE='UTC'

USE_I18N=True

USE_L10N=True

USE_TZ=True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL='/statics/'

STATICFILES_DIRS=[
    os.path.join(BASE_DIR, "statics"),
    os.path.join(BASE_DIR, "statics/css/"),

]

LOGIN_URL="/login/"
LOGIN_REDIRECT_URL='/dashboard/'
LOGOUT_URL='/logout/'

IGNORABLE_404_URLS=(
    re.compile(r'^favicon.ico$'),
    re.compile(r'^/statics/css/bootstrap.min.css.map$')
)

IGNORABLE_200_URLS=(
    re.compile(r'^favicon.ico$'),
    re.compile(r'^/statics/css/bootstrap.min.css.map$')
)

EMAIL_HOST=''
EMAIL_PORT=587
EMAIL_HOST_USER=''
EMAIL_HOST_PASSWORD=''
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL=''

# if DEBUG:
#     INTERNAL_IPS=('127.0.0.1', 'localhost',)
#     MIDDLEWARE_CLASSES+=(
#         'debug_toolbar.middleware.DebugToolbarMiddleware',
#     )
#
#     INSTALLED_APPS+=(
#         'debug_toolbar',
#     )
#
#     DEBUG_TOOLBAR_PANELS=[
#         'debug_toolbar.panels.versions.VersionsPanel',
#         'debug_toolbar.panels.timer.TimerPanel',
#         'debug_toolbar.panels.settings.SettingsPanel',
#         'debug_toolbar.panels.headers.HeadersPanel',
#         'debug_toolbar.panels.request.RequestPanel',
#         'debug_toolbar.panels.sql.SQLPanel',
#         'debug_toolbar.panels.staticfiles.StaticFilesPanel',
#         'debug_toolbar.panels.templates.TemplatesPanel',
#         'debug_toolbar.panels.cache.CachePanel',
#         'debug_toolbar.panels.signals.SignalsPanel',
#         'debug_toolbar.panels.logging.LoggingPanel',
#         'debug_toolbar.panels.redirects.RedirectsPanel',
#     ]
#
#     DEBUG_TOOLBAR_CONFIG={
#         'INTERCEPT_REDIRECTS': False,
#     }
#
# CACHES={
#     'default': {
#         'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#         'LOCATION': 'g:',
#     }
# }
