# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=10, unique=True)),
                ('url', models.TextField()),
                ('user_email', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('is_blocked', models.IntegerField(default=0)),
                ('is_static', models.IntegerField(default=0)),
                ('is_trashed', models.IntegerField(default=0)),
                ('is_del_parmently', models.IntegerField(default=0)),
                ('is_favorite', models.IntegerField(default=0)),
                ('is_arhived', models.IntegerField(default=0)),
                ('category_name', models.CharField(default='', max_length=300)),
                ('domain_name', models.CharField(default='not_defined', max_length=300)),
            ],
        ),
    ]
