# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='category_name',
            field=models.CharField(default='not_defined', max_length=300),
        ),
    ]
