# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170611_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(max_length=300)),
                ('is_blocked', models.IntegerField(default=0)),
                ('category_date_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
