# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='request_status',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(default='not_defined', max_length=300),
        ),
    ]
