# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170614_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='hash',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
