# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_url_md5hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='is_del_parmently',
        ),
        migrations.AddField(
            model_name='url',
            name='is_delete_parmently',
            field=models.IntegerField(default=0),
        ),
    ]
