# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20170618_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='hash',
            new_name='user_hash',
        ),
    ]
