# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170619_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_modified',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='user_email',
            field=models.CharField(max_length=50),
        ),
    ]
