# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20170622_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
