# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_url_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='summary',
            field=models.TextField(default='Not_Defined', null=True),
        ),
    ]
