# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20170625_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='summary',
            new_name='summaryp',
        ),
    ]
